language: node_js
node_js:
  - "0.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - ./node_modules/.bin/start-selenium > reports/selenium.log &
  - sleep 3

script:
  - npm test

after_success:
